### ISSUE TITLE
爬蟲_104人力銀行工作清單 | Tony的學習筆記

### ISSUE THREAD

**Issue by TLYu0419** [TLYu0419/TLYu0419.github.io#1]
https://tlyu0419.github.io/2019/04/18/Crawl-JobList104/#more 

 本文僅限於學習使用，請勿用於商業目的 找工作是一件很辛苦的事情，當我們在104人力銀行的網站上輸入關鍵字查詢職缺時，經常會直接跳出上百、千份的職缺。雖然有很多職缺對於求職者是好事，但這也造成了求職者的大困擾！ 因此我希望能透過Python的爬蟲，一次把我想要查詢的結果(工作內容、地點、薪資、要求技能、工作地點…等等資訊)抓下來，在我自己的電腦上按照我的需求進行篩選，讓我能更有效率的挑選工作並投遞履

**Comment by TLYu0419** [comment]
Hello 測試評論效果

**Comment by jiyuan1202** [comment]
請問Python Version?

**Comment by TLYu0419** [comment]
> @jiyuan1202
> 請問Python Version?
> 

應該是3.6
> @jiyuan1202
> 請問Python Version?
> 
Hello, 應該是3.6的

**Comment by jiyuan1202** [comment]
Thank you

**Comment by jiyuan1202** [comment]
Hello，您好，我是初學者，遇到下面的問題，不知道該怎麼辦
 File "C:\Users\jiyua\source\repos\PythonApplication1\PythonApplication1\PythonApplication1.py", line 100, in <module>
    JobList.to_excel('C:/Users/jiyua/Desktop/JobList2.xlsx', encoding='cp950')
  File "C:\Users\jiyua\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\generic.py", line 2250, in to_excel
    formatter.write(
  File "C:\Users\jiyua\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\formats\excel.py", line 730, in write
    writer = ExcelWriter(_stringify_path(writer), engine=engine)
  File "C:\Users\jiyua\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\excel\_openpyxl.py", line 19, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'

**Comment by jiyuan1202** [comment]
真不好意思，又來問問題
Traceback (most recent call last):
  File "C:\Users\jiyua\source\repos\PythonApplication1\PythonApplication1\PythonApplication1.py", line 100, in <module>
    JobList.to_excel('C:/Users/jiyua/Desktop/JobList2.xlsx', encoding='cp950')
  File "C:\Users\jiyua\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\generic.py", line 2250, in to_excel
    formatter.write(
  File "C:\Users\jiyua\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\formats\excel.py", line 730, in write
    writer = ExcelWriter(_stringify_path(writer), engine=engine)
  File "C:\Users\jiyua\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\excel\_openpyxl.py", line 19, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'

**Comment by TLYu0419** [comment]
> @jiyuan1202
> 真不好意思，又來問問題
> Traceback (most recent call last):
>   File "C:\Users\jiyua\source\repos\PythonApplication1\PythonApplication1\PythonApplication1.py", line 100, in <module>
>     JobList.to_excel('C:/Users/jiyua/Desktop/JobList2.xlsx', encoding='cp950')
>   File "C:\Users\jiyua\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\generic.py", line 2250, in to_excel
>     formatter.write(
>   File "C:\Users\jiyua\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\formats\excel.py", line 730, in write
>     writer = ExcelWriter(_stringify_path(writer), engine=engine)
>   File "C:\Users\jiyua\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\excel\_openpyxl.py", line 19, in __init__
>     from openpyxl.workbook import Workbook
> ModuleNotFoundError: No module named 'openpyxl'

從錯誤的內容顯示"No module named openpyxl"，
所以你輸入 !pip install openpyxl 應該就可以囉

另外跟你詢問一下，你是直接安裝 python 還是透過 Anaconda 安裝 python 呢?
正常都會建議透過 Anaconda 來安裝 python。

**Comment by jiyuan1202** [comment]
> > @jiyuan1202
> > 真不好意思，又來問問題
> > Traceback (most recent call last):
> > File "C:\Users\jiyua\source\repos\PythonApplication1\PythonApplication1\PythonApplication1.py", line 100, in 
> > JobList.to_excel('C:/Users/jiyua/Desktop/JobList2.xlsx', encoding='cp950')
> > File "C:\Users\jiyua\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\generic.py", line 2250, in to_excel
> > formatter.write(
> > File "C:\Users\jiyua\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\formats\excel.py", line 730, in write
> > writer = ExcelWriter(_stringify_path(writer), engine=engine)
> > File "C:\Users\jiyua\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\io\excel_openpyxl.py", line 19, in **init**
> > from openpyxl.workbook import Workbook
> > ModuleNotFoundError: No module named 'openpyxl'
> 
> 從錯誤的內容顯示"No module named openpyxl"，
> 所以你輸入 !pip install openpyxl 應該就可以囉
> 
> 另外跟你詢問一下，你是直接安裝 python 還是透過 Anaconda 安裝 python 呢?
> 正常都會建議透過 Anaconda 來安裝 python。

我是直接安裝python，然後使用VS2017
感謝您的回覆，很抱歉，自己沒有先做好功課，耽誤您的時間；昨晚熬夜測試，這個問題已經處理好了，目前在鑽研其他的項目；網路爬蟲真得很好玩

**Comment by Millshu** [comment]
請問一下 為甚麼我的工作內容 有些字會不見呢

**Comment by TLYu0419** [comment]
> @Millshu
> 請問一下 為甚麼我的工作內容 有些字會不見呢

Hi Millshu
建議參考一下這篇文章，找一下想要抓資料的Element位置，然後微調語法就可以抓到資料囉!
https://tlyu0419.github.io/2019/04/07/Crawl-SongGuo/

**Comment by jackpopp125** [comment]
請問我最近爬取時遇到以下問題:
Click 手動載入，載入第29頁
No more Job
共有 855 筆資料
Fail and Try Again!
Fail and Try Again!
請問該如何解決,謝謝

**Comment by TLYu0419** [comment]
> @jackpopp125
> 請問我最近爬取時遇到以下問題:
> Click 手動載入，載入第29頁
> No more Job
> 共有 855 筆資料
> Fail and Try Again!
> Fail and Try Again!
> 請問該如何解決,謝謝

這邊的程式沒有在維運唷，
建議你可以參考這邊的語法並微調相信就可以排除問題並抓到資料了~

**Comment by TienShentw** [comment]
> @TLYu0419
> > @jackpopp125
> > 請問我最近爬取時遇到以下問題:
> > Click 手動載入，載入第29頁
> > No more Job
> > 共有 855 筆資料
> > Fail and Try Again!
> > Fail and Try Again!
> > 請問該如何解決,謝謝
> 
> 這邊的程式沒有在維運唷，
> 建議你可以參考這邊的語法並微調相信就可以排除問題並抓到資料了~

**Comment by TienShentw** [comment]
`#'工作內容'
soup2.find('p').text`
AttributeError: 'NoneType' object has no attribute 'text'
`#'工作性質'
soup2.select('div.col.p-0.job-description-table__data > p')[2].text`
IndexError: list index out of range
`#'語文條件':
soup2.select('div.col.p-0.job-requirement-table__data > p')[14].text`
IndexError: list index out of range

Hi TLYu0419,

知道您目前這邊程式沒有在維運，
我嘗試修改職缺細項的select,find參數，但還是無法成功抓到資料，
所以冒昧想請教要如何修改才能抓到?或是上面三項提示可成功抓取的寫法，謝謝!

**Comment by TLYu0419** [comment]
> @TienShentw
> `#'工作內容'
> soup2.find('p').text`
> AttributeError: 'NoneType' object has no attribute 'text'
> `#'工作性質'
> soup2.select('div.col.p-0.job-description-table__data > p')[2].text`
> IndexError: list index out of range
> `#'語文條件':
> soup2.select('div.col.p-0.job-requirement-table__data > p')[14].text`
> IndexError: list index out of range
> 
> Hi TLYu0419,
> 
> 知道您目前這邊程式沒有在維運，
> 我嘗試修改職缺細項的select,find參數，但還是無法成功抓到資料，
> 所以冒昧想請教要如何修改才能抓到?或是上面三項提示可成功抓取的寫法，謝謝!

Hi TienShentw
我的建議是你先檢查 soup2 裡面有沒有東西，確認有東西的話再進一步從中解析工作內容、工作性質...資訊
如果有更多需求的話可以寫信給我~
